name: CI
on:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm run test
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [built, committed]
    steps:
      - uses: actions/checkout@v2
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Test create card
        id: coupc-1
        uses: ./
        with:
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          issue-number: 1

      - name: Test card already exists
        uses: ./
        with:
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          issue-number: 1

      - name: Test move card to column
        uses: ./
        with:
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 2
          issue-number: 1

      - name: Delete card
        uses: actions/github-script@0.9.0
        with:
          script: |
            github.projects.deleteCard({
              card_id: ${{ steps.coupc-1.outputs.card-id }}
            })

      - name: Test create card associated with a pull request
        if: github.event_name == 'pull_request'
        id: coupc-2
        uses: ./
        with:
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          issue-number: ${{ github.event.number }}

      - name: Test card already exists with a pull request
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          project-name: '[CI] ${{ matrix.target }}'
          column-name: Test column 1
          issue-number: ${{ github.event.number }}

      - name: Delete card
        if: github.event_name == 'pull_request'
        uses: actions/github-script@0.9.0
        with:
          script: |
            github.projects.deleteCard({
              card_id: ${{ steps.coupc-2.outputs.card-id }}
            })

  package:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Update distribution
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Update distribution
          body: |
            - Updates the distribution for changes on `master`

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-distribution
